spring:
  datasource:
    url: jdbc:h2:mem:testDB
    username: test
    password:
    driverClassName: org.h2.Driver
  jpa:
    hybernate:
      ddl-auto: create
  h2:
    console:
      enabled: true

fileRepositoryFolder: C:\Users\utente\Desktop\FileRepository